### PR TITLE
Patchset on krb5 ccache handling

### LINKED ISSUE #11: auks with keyring credential cache type rather than file type
Hi,

How do I get around where if we use keyring credential cache type for kerberos rather than file type? Right now, it doesn't work until I comment out keyring option in our krb5.conf

default_ccache_name = KEYRING:persistent:%{uid}

Then, by default it's putting cache as file type and things work fine.

Do you have any suggestions? Thanks in advance

Best,
Sreedhar.

### LINKED ISSUE #23: Auks not working with gssproxy tickets, needs private ticket cache
After upgrading to CentOS7.4, auks stopped functioning properly because rpc.gssd stores a GSSPROXY ticket in /tmp/krb5cc_0 (service principal  'Encrypted/Credentials/v1@X-GSSPROXY:') and auks can't use this ticket. Restarting aukspriv will fix the problem temporarily  (new service principal 'krbtgt/DOMAIN@DOMAIN') until rpc.gssd overwrites the cache again.

My workaround is to make auks use it's private ticket cache (/tmp/krb5cc_0_auks). This required quite some searching and trying however:
For aukspriv, I added 'AUKS_PRIV_CCACHE_APPEND=_auks' to /etc/sysconfig/aukspriv.
For auksdrenewer, I added 'KRB5CCNAME=FILE:/tmp/krb5cc_0_auks' to /etc/sysconfig/auksdrenewer.
For the SLURM spank plugin, I added 'hostcredcache=FILE:/tmp/krb5cc_0_auks' to /etc/slurm/plugstack.conf.d/auks.conf.

It would have been nice to have a common setting for this, and even better to use a private ticket cache by default...

### PR DESCRIPTION
**Pull request by fihuer**
This patchset is about making auks agnostic to the underlying ccache type. This touches different parts of auks:
* The auks C API by adding some helper function for ccache management (generation/destruction)
* Aukspriv should not directly manage ccaches, instead it now relies on kinit to do the job
* The Spank plugin, same as aukspriv, it should not directly manage ccaches but only use the api

Fixes #11
May fix #23

### CODE REVIEW

File: src/api/auks/auks_krb5_cred.c [hunk 1]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+	/* Generate a new unique ccache */
+	fstatus = krb5_cc_new_unique(context, ccache_type, NULL, &ccache);
+	if (fstatus) {
+		auks_error("Error while generating new unique ccache of type %s", ccache_type);
+		fstatus = AUKS_ERROR_KRB5_CRED_OPEN_CC ;
+		goto out;
+	}
+
+
+	fstatus = krb5_cc_get_full_name(context, ccache, fullname_out);
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:165]: according to krb5_cc_get_full_name man page, krb5_free_string() must be called on fullname_out when no longer used to free the memory.
As kerberos calls are limited to the scope of this file, it could be good to malloc the string to a traditional char* and call krb5_free_string() directly here on a temporary variable use in krb5_cc_get_full_name.
It should be added to the function description in the header file that the char** must be freed when no longer used to avoid memory leak. It is the responsibility of the caller to do that.

File: src/api/auks/auks_krb5_cred.c [hunk 2]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+	/* Get the default ccache */
+	fstatus = krb5_cc_default(context, &ccache);
+	if (fstatus) {
+	        auks_error("Error while getting default ccache");
+		fstatus = AUKS_ERROR_KRB5_CRED_OPEN_CC ;
+		goto out;
+	}
+
+	/* Get the default ccache type */
+	ccache_type = krb5_cc_get_type(context, ccache);
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:154]: I do not think that it is necessary. See below th cc_switch comment

File: src/api/auks/auks_krb5_cred.c [hunk 3]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+
+	/* Call krb5_cc_switch for ccache that supports if */
+	if (krb5_cc_support_switch(context, ccache_type)) {
+		fstatus = krb5_cc_switch(context, ccache);
+		if (fstatus) {
+			auks_error("Error while calling krb5_cc_switch");
+			fstatus = AUKS_ERROR_KRB5_CRED_OPEN_CC ;
+			goto out;
+		}
+	}
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:181]: this call will have an impact on all the users sessions on the system that will not clearly specify a particular ccache to use using the KRB5CCNAME env variable. I do not think that it is interesting/usefull to put that here.
The goal of the function is to create a new unique ccache for a particular usage, not necessarily to switch all the user session to that ccache.
If this second purpose is required, it should be put in a second function, but I do not think it is necessary for what you have in mind.
The previous comment referring this one correspond to things that could also be removed with that block.

File: src/api/auks/auks_krb5_cred.c [hunk 4]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+
+	/* Free KRB5 context */
+	krb5_free_context(context);
+	return (fstatus);
+}
+
+int
+auks_krb_cc_destroy(char * fullname)
+{
+        int fstatus;
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:196]: bad alignment

File: src/api/auks/auks_krb5_cred.c [hunk 5]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+	krb5_context context;
+	krb5_ccache cache = NULL;
+
+
+	/* Initialize KRB5 context */
+	fstatus = krb5_init_context(&context);
+	if (fstatus) {
+		auks_error("Error while initializing KRB5");
+		fstatus = AUKS_ERROR_KRB5_CRED_INIT_CTX;
+		goto out;
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:207]: in 'out', the context is freed using krb5_free_context(context), we should not jump there here, just return fstatus

File: src/api/auks/auks_krb5_cred.c [hunk 6]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+	}
+
+	fstatus = krb5_cc_destroy(context, cache);
+	if (fstatus && fstatus != KRB5_FCC_NOFILE) {
+		auks_error("Error while destroying cache %s", fullname);
+		fstatus = AUKS_ERROR_KRB5_CRED_READ_CC;
+		goto out;
+	}
+
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:224]: krb5_cc_close is missing here, it must be called to properly manage the cache krb5_ccache handle cleaning.
You can have a look at the auks_krb5_cred_store() to see the closing logic to properly handle krb5_ccache.

File: src/api/auks/auks_krb5_cred.h [hunk 7]
```diff
@@ -212,4 +212,34 @@ int auks_krb5_cred_renew_buffer(char *in_buf,size_t in_buf_len,
 int auks_krb5_cred_deladdr_buffer(char *in_buf,size_t in_buf_len,
 				  char** pout_buf,size_t *pout_buf_len);
 
+
+/*!
+ * \brief Generates a new unique ccache usique krb5_cc_new_unique
+ * \internal
+ *
+ * \param fullanme_out pointer on the newly created ccache
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.h:220]: specify that it is the responsiblity of the caller to free the returning char*

File: src/api/auks/auks_krb5_cred.c [hunk 8]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
 
+int
+auks_krb_cc_new_unique(char ** fullname_out)
+{
+        int fstatus;
+
+        krb5_context context;
+	krb5_ccache ccache;
+
+	char *ccache_type = NULL;
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:135]: I do not think that it is necessary. See below the cc_switch comment

File: src/api/auks/auks_krb5_cred.c [hunk 9]
```diff
@@ -124,6 +124,111 @@ auks_krb_is_local_tgt(krb5_principal princ, krb5_data *realm)
...
+		if (fstatus) {
+			auks_error("Error while calling krb5_cc_switch");
+			fstatus = AUKS_ERROR_KRB5_CRED_OPEN_CC ;
+			goto out;
+		}
+	}
+
+ out:
+	/* Close ccache handles */
+	if (ccache != NULL)
```
Comment (hautreux) [inline src/api/auks/auks_krb5_cred.c:185]: I am not sure that ccache is set to NULL in the libkrb5 in case of error during resolve op, I am not sure this is the right way to handle conditional cleaning. It might work, if krb5_ccache is a pointer and if the compiler explicitely set to 0 any undefined variables. I would not bet on the second to stay true everytime :)
You can have a look at the auks_krb5_cred_store() to see the closing logic to properly handle krb5_ccache.

File: src/plugins/slurm/slurm-spank-auks.c [hunk 10]
```diff
@@ -501,51 +482,68 @@ spank_auks_remote_init (spank_t sp, int ac, char *av[])
...
-		      auks_strerror(fstatus));
-		unlink(auks_credcache);
-		auks_credcache[0]='\0';
+	/* Get auks cred */
+	fstatus = auks_api_get_auks_cred(&engine,uid,&cred);
+	if( fstatus ) {
+		xerror("unable to unpack auks cred from reply : %s",
+		       auks_strerror(fstatus));
+		fstatus = AUKS_ERROR_API_CORRUPTED_REPLY ;
 		goto unload;
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:491]: In case of error, you will jump to unload where you will try to free cred which is not initialized, certainly resulting in a segv or something similar

File: src/plugins/slurm/slurm-spank-auks.c [hunk 11]
```diff
@@ -501,51 +482,68 @@ spank_auks_remote_init (spank_t sp, int ac, char *av[])
...
 
-	/* set cred cache name in user env */
-	fstatus = spank_setenv(sp,"KRB5CCNAME",auks_credcache,1);
-	if ( fstatus != 0 ) {
-		xerror("unable to set KRB5CCNAME env var");
+	if ( seteuid(uid) ) {
+		xerror("unable to switch to user uid : %s",
+		       strerror(errno));
+		goto unload;
 	}
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:505]: setegid+seteuid is not sufficient to avoid some security issues. proper handling of secondary groups using initgroups is necessary.

File: src/plugins/slurm/slurm-spank-auks.c [hunk 12]
```diff
@@ -114,8 +115,7 @@
  */
 SPANK_PLUGIN(auks, 1);
 
-#define CREDCACHE_MAXLENGTH 128
-static char auks_credcache[CREDCACHE_MAXLENGTH];
+static char *auks_credcache = "";
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:118]:
```suggestion
static char *auks_credcache = NULL;
```

File: src/plugins/slurm/slurm-spank-auks.c [hunk 13]
```diff
@@ -445,8 +447,8 @@ spank_auks_remote_init (spank_t sp, int ac, char *av[])
 		break;
 	}
 
-	/* set default auks cred cache length to 0 */
-	auks_credcache[0]='\0';
+	/* Reset auks credcache */
+	auks_credcache = "";
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:451]:
```suggestion
	auks_credcache = NULL;
```

File: src/plugins/slurm/slurm-spank-auks.c [hunk 14]
```diff
@@ -501,51 +482,68 @@ spank_auks_remote_init (spank_t sp, int ac, char *av[])
...
-			free(prev_krb5ccname);
-		} else {
-			unsetenv("KRB5CCNAME");
-		}
+	fstatus = auks_krb_cc_new_unique(&auks_credcache);
+	if (fstatus) {
+	        xerror("Error while initializing a new unique");
+		goto unload;
+	}
+
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:512]: starting from here, you are supposed to free auks_credcache at some point or you get a memleak.

File: src/plugins/slurm/slurm-spank-auks.c [hunk 15]
```diff
@@ -572,10 +570,10 @@ spank_auks_remote_exit (spank_t sp, int ac, char **av)
 		return (0);
 
 	/* only process if a cred file was defined in a previous call */
-	if ( strnlen(auks_credcache,CREDCACHE_MAXLENGTH) == 0 )
+	if ( strlen(auks_credcache) == 0 )
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:573]:
```suggestion
	if ( auks_credcache == NULL )
```

File: src/plugins/slurm/slurm-spank-auks.c [hunk 16]
```diff
@@ -589,31 +587,33 @@ spank_auks_remote_exit (spank_t sp, int ac, char **av)
...
+	fstatus = auks_krb_cc_destroy(auks_credcache);
+	if (fstatus) {
+	      xerror("Unable to destroy ccache %s",auks_credcache);
+	      goto err;
 	}
-	else
-		xinfo("user '%u' cred cache %s removed",uid,auks_credcache);
 
+        xinfo("Destroyed ccache %s", auks_credcache);
+
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:615]: this is probably here that you should free auks_credcache and set it back to NULL.

File: src/plugins/slurm/slurm-spank-auks.c [hunk 17]
```diff
@@ -501,51 +482,68 @@ spank_auks_remote_init (spank_t sp, int ac, char *av[])
...
+		xerror("unable to set KRB5CCNAME env var");
+
 unload:
+	/* Free auks cred */
+	auks_cred_free_contents(&cred);
+
+	/* reset privileged uid/gid */
+	seteuid(getuid());
+	setegid(getgid());
+
```
Comment (hautreux) [inline src/plugins/slurm/slurm-spank-auks.c:542]: you should reset also the initial secondary groups here

Comment (fihuer) [reply src/plugins/slurm/slurm-spank-auks.c:542]: Auks never touched the secondary groups here. It could but that's much more work. The method haven't changed in this patchset.

File: src/api/auks/auks_krb5_cred.c (hunk 3 above)
Comment (fihuer) [reply src/api/auks/auks_krb5_cred.c:181]: In theory it seems like that. It should not be done. But in the case that the newly created ccache in the only one present, without that call, the object representing the default ccache of the collection is not created.
That makes me think that it only works when you have that particular environment variable. 
ie. It this creates the KCM:%{euid}:XXXX ccache, I do not think that KCM:%{euid} points to something usable.
This is clearly a corner case. Maybe, this call make the whole thing work if you don't have that `KRB5CCNAME` variable.
OpenSSH already does that, ccache are set as default on each and every new session. It creates a new one and call `krb5_cc_switch` onto it.

Comment (fihuer) [reply src/api/auks/auks_krb5_cred.c:181]: On the other hand, if the session have a `KRB5CCNAME` pointing to a valid ccache, the default ccache of the collection is never used.
Thus, if all sessions of a user have a `KRB5CCNAME` env variable set, this is useless.

File: src/api/auks/auks_krb5_cred.c [hunk 18]
```diff
@@ -100,6 +100,30 @@
 #include "auks/auks_krb5_cred.h"
 #include "auks/auks_log.h"
 
+/* Some data comparison and conversion functions.  */
+static inline int
+auks_krb_data_eq(krb5_data d1, krb5_data d2)
```
[the remark this answers is not in the document]
Comment (fihuer) [reply src/api/auks/auks_krb5_cred.c:105]: Done

File: src/api/auks/auks_krb5_cred.c [hunk 19]
```diff
@@ -100,6 +100,30 @@
...
+{
+	return (d1.length == d2.length && (d1.length == 0 ||
+					   !memcmp(d1.data, d2.data, d1.length)));
+}
+
+static inline int
+auks_krb_data_eq_string (krb5_data d, const char *s)
```
[the remark this answers is not in the document]
Comment (fihuer) [reply src/api/auks/auks_krb5_cred.c:112]: Done

File: src/plugins/slurm/slurm-spank-auks.c (hunk 11 above)
Comment (fihuer) [reply src/plugins/slurm/slurm-spank-auks.c:505]: See https://github.com/hautreux/auks/pull/38#discussion_r425643871

**Comment by hautreux** [comment]
Let's try it
